[package]
name = "executor"
version.workspace = true
edition.workspace = true

[dependencies]
kernel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
nodes-core = { workspace = true }
async-trait = { workspace = true }
envelope = { workspace = true }

