[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
kernel = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
tempfile = "3.10"
libc = "0.2"
async-trait = { workspace = true }
